# Generated by Django 3.1.6 on 2021-02-19 02:10

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dob', models.DateField(max_length=8)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('code', models.TextField()),
                ('photo_license', models.ImageField(blank=True, null=True, upload_to=patient.models.get_image_path)),
                ('appointment', models.DateTimeField()),
            ],
        ),
    ]
