# Generated by Django 3.1.6 on 2021-02-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='code',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='province',
            new_name='zipcode',
        ),
    ]
