# Generated by Django 3.1.6 on 2021-02-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210219_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment',
            field=models.DateTimeField(),
        ),
    ]
